name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - grass
  - gradio
  - pip
  - vim
  - pip:
    - grass-session
    # - pytest
    # - pytest-testinfra
    # - pytest-testinfra[podman]